[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html
    --capture=tee-sys
markers =
    smoke: smoke test
    db: cần kết nối DB
    admin: chạy trên Django admin
    fe: chạy trên frontend React
