# Generated by Django 4.2.24 on 2025-12-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatbot_cha_user_id_ac2c89_idx',
            old_name='chatbot_cha_user_id_timestamp_idx',
        ),
    ]
