# Generated by Django 4.2.24 on 2025-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='example',
            new_name='example_en',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='example_vi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
