# Generated by Django 4.2.24 on 2025-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_rename_example_vocabulary_example_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
