# Generated by Django 4.2.24 on 2025-10-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_course_image_url_course_is_favorite_topic_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='word_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
