# Generated by Django 4.2.24 on 2025-11-21 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0004_vocabulary_word_type'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourseprogress',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterModelOptions(
            name='usertopicprogress',
            options={'ordering': ['-last_attempt_at']},
        ),
        migrations.AlterModelOptions(
            name='uservocabularymastery',
            options={'ordering': ['-last_practiced_at']},
        ),
        migrations.AddField(
            model_name='uservocabularymastery',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='uservocabularymastery',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uservocabularymastery',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservocabularymastery',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uservocabularymastery',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='usertopicprogress',
            unique_together={('user', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='uservocabularymastery',
            unique_together={('user', 'vocabulary')},
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
