# Generated by Django 4.2.24 on 2025-11-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_usercourseprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='new_words_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='review_words_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
