# Generated by Django 4.2.24 on 2025-12-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_dailyactivity_new_words_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='new_words_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='review_words_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
