# Generated by Django 4.2.24 on 2026-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
