[pytest]
DJANGO_SETTINGS_MODULE = core.settings_test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = students vocabulary progress chatbot learning
addopts =
    --cov=students
    --cov=vocabulary
    --cov=progress
    --cov=chatbot
    --cov=learning
    --cov-config=.coveragerc
    --cov-report=term-missing
    --cov-report=html:htmlcov
    -v
